### ISSUE TITLE
Got this crash

### ISSUE THREAD

**Issue by probonopd** [lekma/plugin.video.invidious#47] opened 2021-01-03 23:37 UTC
```
2021-01-04 00:34:04.699 T:3773907824  NOTICE: [plugin.video.invidious] request.url: https://invidious.snopyta.org/api/v1/playlists/PLoFRvPlmME6H2FWTcK4Aru8gL8XzP9LjC?region=US
2021-01-04 00:34:05.949 T:3425031024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'iapc.json_service.RequestError'>
                                            Error Contents: remote traceback: unknown error
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 216, in <module>
                                                dispatch(*sys.argv)
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 212, in dispatch
                                                InvidiousPlugin(url, int(handle)).dispatch(**parseQuery(query))
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 33, in dispatch
                                                super(InvidiousPlugin, self).dispatch(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/tools/plugin.py", line 68, in dispatch
                                                return action(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/tools/plugin.py", line 29, in wrapper
                                                success = func(self, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 158, in autogenerated
                                                client.autogenerated(**kwargs), "playlist", **kwargs
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/invidious/client.py", line 146, in autogenerated
                                                data = self.__client__.autogenerated(authorId, **kwargs)
                                              File "/storage/.kodi/addons/script.module.iapc/lib/iapc/json_service.py", line 174, in __call__
                                                return Request(self.sender).execute((self.name, args, kwargs))
                                              File "/storage/.kodi/addons/script.module.iapc/lib/iapc/json_service.py", line 153, in execute
                                                raise self.response
                                            RequestError: remote traceback: unknown error
                                            -->End of Python script error report<--
```

System information:

```
LibreELEC:~/.kodi/addons # cat /etc/os-release 
NAME="LibreELEC"
VERSION="9.0.2"
ID="libreelec"
VERSION_ID="9.0"
PRETTY_NAME="LibreELEC (official): 9.0.2"
HOME_URL="https://libreelec.tv"
BUG_REPORT_URL="https://github.com/LibreELEC/LibreELEC.tv"
BUILD_ID="301789032e264eac90589cdf0c094c557cec43fb"
OPENELEC_ARCH="LePotato.arm"
LIBREELEC_ARCH="LePotato.arm"
LIBREELEC_BUILD="official"
LIBREELEC_PROJECT="Amlogic"
LIBREELEC_DEVICE="LePotato"
```

**Comment by lekma** [comment] 2021-01-04 06:23
crash? did it crash kodi? really? that bad?

Was there anything else relevant in the log before the excerpt you posted? Because, from what I can see, the error probably happenend because snopyta timed out. Would you mind trying to reproduce whatever lead you to this error and use https://paste.kodi.tv/ to post the log. In the meantime I'll try and implement better error logging for timeouts.

thanks for your help

**Comment by probonopd** [comment] 2021-01-04 06:38
Thanks @lekma. I don't have this log anymore but I will post if it happens again.

**Comment by SethFalco** [comment] 2023-06-06 08:03
Given that this seemingly hasn't occurred in over 2 years, and the code has changed quite significantly since the stack trace, maybe it's worth closing this?

There have been various updates across software and dependencies since posted, so it could be it was incidentally fixed. Once it occurs again and there is enough information that this is actually actionable, then we can work towards resolving it.

Next time, more context and the logs would be helpful, though. (What did you do to lead up to that error, and more logs.)

**Closed** 2023-06-07 07:56 UTC
